import { BeatEvent } from '../types';

export const parseScript = (script: string): BeatEvent[] => {
  const lines = script.split('\n');
  const events: BeatEvent[] = [];
  let idCounter = 0;
  
  // Map to store tone definitions: 'name' -> { carrier, beat, vol }
  const definitions: Record<string, { carrier: number, beat: number, vol: number }> = {};

  // Regex helpers
  // Matches definition: name: carrier+beat/vol
  // e.g., "alpha: 200+10/50"
  const defRegex = /^([a-zA-Z0-9_]+):\s+([\d.]+)\+([\d.]+)\/([\d.]+)/;
  
  // Matches time start: MM:SS or HH:MM:SS
  const timeStartRegex = /^(\d{1,2}):(\d{2})(?::(\d{2}))?/;
  
  // Matches explicit tone: carrier+beat/vol
  const toneRegex = /([\d.]+)\+([\d.]+)\/([\d.]+)/;

  lines.forEach((line) => {
    // Remove comments and whitespace
    const commentIndex = line.indexOf('#');
    const text = (commentIndex >= 0 ? line.substring(0, commentIndex) : line).trim();
    
    if (!text) return;

    // Check for definition assignment
    const defMatch = text.match(defRegex);
    if (defMatch) {
      definitions[defMatch[1]] = {
        carrier: parseFloat(defMatch[2]),
        beat: parseFloat(defMatch[3]),
        vol: parseFloat(defMatch[4])
      };
      return; 
    }

    // Check for Time Line
    const timeMatch = text.match(timeStartRegex);
    if (timeMatch) {
      let hours = 0, minutes = 0, seconds = 0;
      
      // Determine MM:SS or HH:MM:SS
      if (timeMatch[3]) {
        hours = parseInt(timeMatch[1], 10);
        minutes = parseInt(timeMatch[2], 10);
        seconds = parseInt(timeMatch[3], 10);
      } else {
        minutes = parseInt(timeMatch[1], 10);
        seconds = parseInt(timeMatch[2], 10);
      }
      const totalSeconds = hours * 3600 + minutes * 60 + seconds;

      // Extract the part after the time string
      const remainder = text.substring(timeMatch[0].length).trim();
      
      let carrier = 0, beat = 0, vol = 0;
      let found = false;

      // Split remainder into words to check for variable names
      const words = remainder.split(/\s+/);
      const firstWord = words[0];

      // Case 1: Reference to a definition (e.g., "00:00 alpha")
      if (firstWord && definitions[firstWord]) {
          const def = definitions[firstWord];
          carrier = def.carrier;
          beat = def.beat;
          vol = def.vol;
          found = true;
      } 
      // Case 2: Explicit definition (e.g., "00:00 200+10/50")
      else {
          const toneMatch = remainder.match(toneRegex);
          if (toneMatch) {
              carrier = parseFloat(toneMatch[1]);
              beat = parseFloat(toneMatch[2]);
              vol = parseFloat(toneMatch[3]);
              found = true;
          }
      }

      if (found) {
        events.push({
            id: `evt_${idCounter++}_${Date.now()}`,
            timeOffset: totalSeconds,
            carrierFreq: carrier,
            beatFreq: beat,
            volume: vol,
        });
      } else if (firstWord === 'off' || firstWord === '.') {
         // Handle 'off' or '.' as silence
         events.push({
            id: `evt_${idCounter++}_${Date.now()}`,
            timeOffset: totalSeconds,
            carrierFreq: 0,
            beatFreq: 0,
            volume: 0,
        });
      }
    }
  });

  return events.sort((a, b) => a.timeOffset - b.timeOffset);
};

export const generateScript = (events: BeatEvent[]): string => {
  let script = "# Generated by BinauralForge\n# Time Carrier+Beat/Volume\n\n";
  
  events.forEach(evt => {
    const h = Math.floor(evt.timeOffset / 3600);
    const m = Math.floor((evt.timeOffset % 3600) / 60);
    const s = Math.floor(evt.timeOffset % 60);
    
    // Format: HH:MM:SS or MM:SS
    let timeStr = "";
    if (h > 0) {
        timeStr = `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
    } else {
        timeStr = `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
    }
    
    script += `${timeStr} ${evt.carrierFreq.toFixed(1)}+${evt.beatFreq.toFixed(2)}/${evt.volume.toFixed(1)}\n`;
  });

  return script;
};